In [1]:
import pandas as pd
df=pd.read_csv(r"D:\machine_learning_project\Housing\archive\housing_price_dataset.csv")

In [2]:
df

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [3]:
df.isna().any()

SquareFeet      False
Bedrooms        False
Bathrooms       False
Neighborhood    False
YearBuilt       False
Price           False
dtype: bool

In [5]:
dummies=pd.get_dummies(df.Neighborhood)
dummies

Rural  Suburb  Urban
0          1       0      0
1          1       0      0
2          0       1      0
3          0       0      1
4          0       1      0
...      ...     ...    ...
49995      1       0      0
49996      0       1      0
49997      0       1      0
49998      1       0      0
49999      1       0      0

[50000 rows x 3 columns]

In [7]:
merged_data=pd.concat([df,dummies],axis='columns')

In [8]:
merged_data

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price  \
0            2126         4          1        Rural       1969  215355.283618   
1            2459         3          2        Rural       1980  195014.221626   
2            1860         2          1       Suburb       1970  306891.012076   
3            2294         2          1        Urban       1996  206786.787153   
4            2130         5          2       Suburb       2001  272436.239065   
...           ...       ...        ...          ...        ...            ...   
49995        1282         5          3        Rural       1975  100080.865895   
49996        2854         2          2       Suburb       1988  374507.656727   
49997        2979         5          3       Suburb       1962  384110.555590   
49998        2596         5          2        Rural       1984  380512.685957   
49999        1572         5          3        Rural       2011  221618.583218   

       Rural  Suburb  Urban  
0          1       0      0  
1          1       0      0  
2          0       1      0  
3          0       0      1  
4          0       1      0  
...      ...     ...    ...  
49995      1       0      0  
49996      0       1      0  
49997      0       1      0  
49998      1       0      0  
49999      1       0      0  

[50000 rows x 9 columns]

In [10]:
 final=merged_data.drop(['Neighborhood','Urban'],axis='columns')

In [11]:
final

SquareFeet  Bedrooms  Bathrooms  YearBuilt          Price  Rural  \
0            2126         4          1       1969  215355.283618      1   
1            2459         3          2       1980  195014.221626      1   
2            1860         2          1       1970  306891.012076      0   
3            2294         2          1       1996  206786.787153      0   
4            2130         5          2       2001  272436.239065      0   
...           ...       ...        ...        ...            ...    ...   
49995        1282         5          3       1975  100080.865895      1   
49996        2854         2          2       1988  374507.656727      0   
49997        2979         5          3       1962  384110.555590      0   
49998        2596         5          2       1984  380512.685957      1   
49999        1572         5          3       2011  221618.583218      1   

       Suburb  
0           0  
1           0  
2           1  
3           0  
4           1  
...       ...  
49995       0  
49996       1  
49997       1  
49998       0  
49999       0  

[50000 rows x 7 columns]

In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [17]:
x_train=final.drop(['Price'],axis='columns')
x_train

SquareFeet  Bedrooms  Bathrooms  YearBuilt  Rural  Suburb
0            2126         4          1       1969      1       0
1            2459         3          2       1980      1       0
2            1860         2          1       1970      0       1
3            2294         2          1       1996      0       0
4            2130         5          2       2001      0       1
...           ...       ...        ...        ...    ...     ...
49995        1282         5          3       1975      1       0
49996        2854         2          2       1988      0       1
49997        2979         5          3       1962      0       1
49998        2596         5          2       1984      1       0
49999        1572         5          3       2011      1       0

[50000 rows x 6 columns]

In [18]:
y_train=final.Price
y_train

0        215355.283618
1        195014.221626
2        306891.012076
3        206786.787153
4        272436.239065
             ...      
49995    100080.865895
49996    374507.656727
49997    384110.555590
49998    380512.685957
49999    221618.583218
Name: Price, Length: 50000, dtype: float64

In [19]:
reg.fit(x_train,y_train)

LinearRegression()

In [21]:
reg.predict([[8000,4,2,1998,0,1]])

C:\Users\rupal\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([821689.49406784])

In [22]:
reg.score(x_train,y_train)

0.5702241893036348

In [ ]:
#One hot encoder using label encoding


In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [25]:
dfle=df
le.fit_transform(dfle.Neighborhood)

array([0, 0, 1, ..., 1, 0, 0])

In [26]:
dfle

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [28]:
dfle.Neighborhood=le.fit_transform(dfle.Neighborhood)

In [29]:
dfle

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0            2126         4          1             0       1969  215355.283618
1            2459         3          2             0       1980  195014.221626
2            1860         2          1             1       1970  306891.012076
3            2294         2          1             2       1996  206786.787153
4            2130         5          2             1       2001  272436.239065
...           ...       ...        ...           ...        ...            ...
49995        1282         5          3             0       1975  100080.865895
49996        2854         2          2             1       1988  374507.656727
49997        2979         5          3             1       1962  384110.555590
49998        2596         5          2             0       1984  380512.685957
49999        1572         5          3             0       2011  221618.583218

[50000 rows x 6 columns]

In [31]:
x_train=dfle.drop('Price',axis='columns')
#constructing 2d array
X=df[['SquareFeet','Bedrooms','Bathrooms','Neighborhood','YearBuilt']].values
y_train=dfle.Price

In [32]:
X

array([[2126,    4,    1,    0, 1969],
       [2459,    3,    2,    0, 1980],
       [1860,    2,    1,    1, 1970],
       ...,
       [2979,    5,    3,    1, 1962],
       [2596,    5,    2,    0, 1984],
       [1572,    5,    3,    0, 2011]], dtype=int64)

In [49]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

A = make_column_transformer(
    (OneHotEncoder(), [0]), 
    remainder="passthrough")

X_ohe=A.fit_transform(X)

In [50]:
ohe

OneHotEncoder(categories=[0])

In [51]:
X_ohe

<50000x2004 sparse matrix of type '<class 'numpy.float64'>'
	with 233324 stored elements in Compressed Sparse Row format>

In [41]:
X_ohe

<50000x2082 sparse matrix of type '<class 'numpy.float64'>'
	with 250000 stored elements in Compressed Sparse Row format>

In [52]:
X_ohe=X_ohe.toarray()

In [53]:
X_ohe

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        1.969e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.000e+00, 0.000e+00,
        1.980e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        1.970e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.000e+00, 1.000e+00,
        1.962e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.000e+00, 0.000e+00,
        1.984e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.000e+00, 0.000e+00,
        2.011e+03]])

In [44]:
reg.fit(X_ohe,y_train)

LinearRegression()

In [45]:
reg.predict([[8000,4,2,1998,0,1]])

ValueError: X has 6 features, but LinearRegression is expecting 2082 features as input.